---
kind: pipeline
name: default

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: registry.thinkit.ir/teletin
      tags: latest
      dockerfile: .docker/Dockerfile.local

trigger:
  branch:
    - master
